spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 923166838773-fg4qceskfhs5dj4c9a02790674ognipb.apps.googleusercontent.com
            clientSecret: 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


logging:
  level:
    root: debug