spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: testapp
          client-secret: 123456
          introspection-uri: http://localhost:8080/oauth/check_token
      client:
        registration:
          google:
            clientId: 923166838773-fg4qceskfhs5dj4c9a02790674ognipb.apps.googleusercontent.com
            clientSecret: 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
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"

custom:
  oauth2:
    kakao:
      client-id: b8a3b3c35c7d32a96ed9f6531388f198
      client-secret: leVz1yws2bq7v8QT31CsTv3MUaAKGnZ1
      redirect-uri: "{baseUrl}/login/oauth2/callback/{registrationId}"
      client-authentication-method: POST
      authorization-grant-type: authorization_code
      scope: profile_nickname, profile_image, account_email
      client-name: Kakao


logging:
  level:
    root: debug